version: '2'
services:
  finder-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_URL:${MYSQL_URL}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
    ports:
      - 3306:3306
    env_file:
      - .env